### ISSUE TITLE
Coloring of Cooperations not complete

### ISSUE THREAD

**Issue by olsch88** [jamesjonesphoenix/X3-Colour-By-Race#2]
Some cooperation assets are not colored, while others are. (Using the German version)
Screenshot 1: Terracorp HQ is colored, but the ships are not:
![grafik](https://user-images.githubusercontent.com/95592115/236929593-96d7ad67-3a55-4e55-a3a3-7801f53cb849.png)

Screenshot 2: Atreus HQ is colored, but the Shipyard and the ships are not:
![grafik](https://user-images.githubusercontent.com/95592115/236929833-dcff2376-5077-4531-9e8a-ee43c533da5d.png)

All races are colored as expected, both ships and stations.

**Comment by jamesjonesphoenix** [comment]
Hi Olsch, thanks for the report - after some investigation I think I know what is causing this. I'm currently working on an update which will include a fix. 

Cycrow has been frequently updating the FL unofficial patch. At some point he changed the engine version from 61 to 62. Colour by Race is checking for FL by checking the engine version is equal to 61. This check would now fail leading to the mod not checking for FL corporation objects. I'll be changing this check to check for any engine version greater or equal than 61.

Could you please let me know which version of Cycrow's unofficial patch you were using when taking the screenshots?

**Comment by olsch88** [comment]
I try to keep my game up to date. So it should be 1.3.7 (Version from 2023-05-01).
The issue persists in version 1.3.8.

**Comment by jamesjonesphoenix** [comment]
Thanks! Yes those versions would trigger the problem I'm talking about. I am working on the next version of Colour By Race which will fix the bug. 

If you want a temporary fix you can download the latest `plugin.jj.colour.by.race.get.races.xml` file and overwrite the old one in your addon2/scripts folder. Then load your save game, deactivate Colour By Race and reactivate it. Otherwise wait for the new release - should be coming soon.

**Comment by jamesjonesphoenix** [comment]
I've finally updated the plugin to version 1.3. Can you give it a try and let me know if it fixes the corporations for you?

**Comment by olsch88** [comment]
Is it sufficient, if I turn the plugin off and on again after installing
the new version? Will try it later today.

James Jones ***@***.***> schrieb am Do., 1. Juni 2023, 18:34:

**Comment by jamesjonesphoenix** [comment]
You shouldn't need to do that. It will detect the version has changed, strip all the colours and redo them across the galaxy.

You can of course deactivate and reactivate the plugin if you like.

**Comment by olsch88** [comment]
So far, the cooperations are all colored correctly.
The only thing I could still spot is the "militärischer" being only partially colored. 
The changelog mentioned, that you got this covered, 
Example: 
![grafik](https://github.com/jamesjonesphoenix/colour-by-race/assets/95592115/4db0858e-29e0-4fe2-832d-6ddae88cac2d)

**Comment by jamesjonesphoenix** [comment]
Thanks for spotting - just released 1.3.1 which fixes this bug.

I did have "militärischer" covered but the plugin would accidentally delete all search strings when it noticed the plugin had been updated. So no objects would actually get reset and therefore was impossible to re-colour.

If you deactivated and reactivated the plugin this would have reset correctly. But that's not ideal. 

While I was experimenting (I installed German version on my PC for testing) I noticed "Piratenhafen" has just the "Piraten" part coloured. Would you prefer the whole word be coloured?

**Comment by olsch88** [comment]
Installed 1.3.1
Looks good now on the sector map. But sadly, I found another bug. When I go to the encyclopedia and open the "docks" section, I get this picture:
![grafik](https://github.com/jamesjonesphoenix/colour-by-race/assets/95592115/f4e23d42-6526-4b40-af28-5ec526781508)

This does not change after deactivating and reactivating the mod. Probably because the stations get added there when they are encountered for the first time. 

Regarding your last question: Personally, I think that coloring whole names looks better.

**Comment by jamesjonesphoenix** [comment]
Roger that, I'll colour the whole pirate station name in the next version.

With the encyclopedia, that's not really a bug. The encyclopedia doesn't look directly at the name of the station you discovered, it simply grabs the t file string for a station. I've overwritten many t file entries for station names with coloured versions in the 9965 t file you helped translate which is what the encyclopedia is reading.

For something like a trading station, each race has it's own individual t file entry so I can colour it in the t file. But for the military bases, every race uses the same t file entry. So I can't colour it in the t file because it would be wrong for most races.

However the only reason I was overwriting t file entries for stations in the first place was because I couldn't detect when a station was first created. I wanted to avoid a long delay where the station remained uncoloured so I changed t file entries where I could. In FL I don't really need this because I have SIGNAL_CREATED available which detects new stations immediately. I'm now using this signal for colouring new stations. 

So in a future version I will probably rejig the code so those coloured station t file entries are only used in AP and TC. This will mean there will be no coloured station names in the encyclopedia which will be more consistent.

**Comment by olsch88** [comment]
Well then, I guess this issue is solved. Thank you.
